name: Cypress Tests 

on: 
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  running_cypress:
    name: Running cypress tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 16.14.0
      - name: Install yarn dependecies
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          browser: chrome
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 3000
      - name: Copy test execution videos and screenshots
        if: always ()
        run: |
          mkdir results
          cp -r cypress/videos results/videos
          cp -r cypress/screenshots results/screenshots
      - name: Merge test results into one
        if: always ()
        run: yarn run report:merge
      - name: Generate HTML report
        if: always ()
        run: yarn run report:generate
      - name: Save results as test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-results
          path: |
            results
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' || always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results
          destination_dir: ${{ GITHUB_REF_NAME }}/${{ GITHUB_RUN_NUMBER }}