name: Cypress Tests with installation job

on: 
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 16.14.0
      - name: Install yarn dependecies
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 300