name: Cypress Tests 

on: 
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  running_cypress:
    name: Running cypress tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 16.14.0
      - name: Install yarn dependecies
        run: yarn
      - name: Run application
        run: yarn start &
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          browser: chrome
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 300